<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ContactMessage;

/**
 * ContactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(ContactMessage $contactMessage)
    {
        $this->_em->persist($contactMessage);
        $this->_em->flush();
    }
}
