<?php

namespace AppBundle\Repository;


/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends \Doctrine\ORM\EntityRepository
{
    public function createIndex()
    {
        $qb = $this->createQueryBuilder('o');
        $qb->select(array( 'o', 'd'))
            ->join('o.doctor', 'd');

        return $qb;
    }
}
