<?php

namespace AppBundle\Repository;

/**
 * PaymentMeanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMeanRepository extends \Doctrine\ORM\EntityRepository
{
}
