fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                office:
                    mappings:
                        id: ~
                        name:
                            type: string
                            index: not_analyzed
                            copy_to: [tags]
                        slug: ~
                        address: ~
                        typeText: ~
                        isSponsored:
                            type: boolean
                            index: not_analyzed
                        isEnabled: ~
                        city:
                            type: object
                            properties:
                                id:
                                    type: string
                                    index: not_analyzed
                                name:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                        region:
                            type: object
                            properties:
                                id:
                                    type: string
                                    index: not_analyzed
                                name:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                                slug:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                        doctors:
                            type: object
                            properties:
                                id:
                                    type: string
                                    index: not_analyzed
                                insurance:
                                    type: boolean
                                    index: not_analyzed
                                firstname:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                                lastname:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                                slug:
                                    type: string
                                    index: not_analyzed
                                    copy_to: [tags]
                                schedule: ~
                                waitingTime:
                                    type: date
                                    index: not_analyzed
                                languages:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                            index: not_analyzed
                                            copy_to: [tags]
                                specialities:
                                    type: object
                                    properties:
                                        id:
                                            type: string
                                            index: not_analyzed
                                        name:
                                            type: string
                                            index: not_analyzed
                                            copy_to: [tags]
                                        slug:
                                            type: string
                                            index: not_analyzed
                                            copy_to: [tags]
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Office
                        finder: ~
                        provider: ~
                        listener: ~
