fos_elastica:
    indexes:
        app:
            types:
                office:
                    mappings:
                        name: ~
                        slug: ~
                        address: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: AppBundle\Entity\Office
                        provider: ~
                        finder: ~
