doctoubib_models_doctor:
    resource: "@DoctoubibModelsBundle/Controller/DoctorController.php"
    type:     annotation

doctoubib_models_insurance:
    resource: "@DoctoubibModelsBundle/Controller/InsuranceController.php"
    type:     annotation

doctoubib_models_speciality:
    resource: "@DoctoubibModelsBundle/Controller/SpecialityController.php"
    type:     annotation

doctoubib_models:
    resource: "@DoctoubibModelsBundle/Resources/config/routing.yml"
    prefix:   /

ws:
    resource: "@WsBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc