app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '.'
    type: 'api_platform'

api_login_check:
    path: /api/login_check

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"